#!/usr/bin/env python

import os
import sys
for d in filter(lambda x: x.startswith('lib.'), os.listdir('build')):
    sys.path.append(os.path.sep.join([os.getcwd(), 'build', d]))
import SDL

def check_const(name):
    return getattr(SDL, name)

check_const('INIT_TIMER')
check_const('INIT_VIDEO')
check_const('INIT_AUDIO')
check_const('INIT_CDROM')
check_const('INIT_JOYSTICK')
check_const('INIT_EVERYTHING')
check_const('INIT_NOPARACHUTE')
check_const('INIT_EVENTTHREAD')

check_const('ENOMEM')
check_const('EFREAD')
check_const('EFWRITE')
check_const('EFSEEK')
check_const('UNSUPPORTED')
check_const('LASTERROR')

check_const('K_UNKNOWN')
check_const('K_FIRST')
check_const('K_BACKSPACE')
check_const('K_TAB')
check_const('K_CLEAR')
check_const('K_RETURN')
check_const('K_PAUSE')
check_const('K_ESCAPE')
check_const('K_SPACE')
check_const('K_EXCLAIM')
check_const('K_QUOTEDBL')
check_const('K_HASH')
check_const('K_DOLLAR')
check_const('K_AMPERSAND')
check_const('K_QUOTE')
check_const('K_LEFTPAREN')
check_const('K_RIGHTPAREN')
check_const('K_ASTERISK')
check_const('K_PLUS')
check_const('K_COMMA')
check_const('K_MINUS')
check_const('K_PERIOD')
check_const('K_SLASH')
check_const('K_0')
check_const('K_1')
check_const('K_2')
check_const('K_3')
check_const('K_4')
check_const('K_5')
check_const('K_6')
check_const('K_7')
check_const('K_8')
check_const('K_9')
check_const('K_COLON')
check_const('K_SEMICOLON')
check_const('K_LESS')
check_const('K_EQUALS')
check_const('K_GREATER')
check_const('K_QUESTION')
check_const('K_AT')

check_const('K_LEFTBRACKET')
check_const('K_BACKSLASH')
check_const('K_RIGHTBRACKET')
check_const('K_CARET')
check_const('K_UNDERSCORE')
check_const('K_BACKQUOTE')
check_const('K_a')
check_const('K_b')
check_const('K_c')
check_const('K_d')
check_const('K_e')
check_const('K_f')
check_const('K_g')
check_const('K_h')
check_const('K_i')
check_const('K_j')
check_const('K_k')
check_const('K_l')
check_const('K_m')
check_const('K_n')
check_const('K_o')
check_const('K_p')
check_const('K_q')
check_const('K_r')
check_const('K_s')
check_const('K_t')
check_const('K_u')
check_const('K_v')
check_const('K_w')
check_const('K_x')
check_const('K_y')
check_const('K_z')
check_const('K_DELETE')

check_const('K_WORLD_0')
check_const('K_WORLD_1')
check_const('K_WORLD_2')
check_const('K_WORLD_3')
check_const('K_WORLD_4')
check_const('K_WORLD_5')
check_const('K_WORLD_6')
check_const('K_WORLD_7')
check_const('K_WORLD_8')
check_const('K_WORLD_9')
check_const('K_WORLD_10')
check_const('K_WORLD_11')
check_const('K_WORLD_12')
check_const('K_WORLD_13')
check_const('K_WORLD_14')
check_const('K_WORLD_15')
check_const('K_WORLD_16')
check_const('K_WORLD_17')
check_const('K_WORLD_18')
check_const('K_WORLD_19')
check_const('K_WORLD_20')
check_const('K_WORLD_21')
check_const('K_WORLD_22')
check_const('K_WORLD_23')
check_const('K_WORLD_24')
check_const('K_WORLD_25')
check_const('K_WORLD_26')
check_const('K_WORLD_27')
check_const('K_WORLD_28')
check_const('K_WORLD_29')
check_const('K_WORLD_30')
check_const('K_WORLD_31')
check_const('K_WORLD_32')
check_const('K_WORLD_33')
check_const('K_WORLD_34')
check_const('K_WORLD_35')
check_const('K_WORLD_36')
check_const('K_WORLD_37')
check_const('K_WORLD_38')
check_const('K_WORLD_39')
check_const('K_WORLD_40')
check_const('K_WORLD_41')
check_const('K_WORLD_42')
check_const('K_WORLD_43')
check_const('K_WORLD_44')
check_const('K_WORLD_45')
check_const('K_WORLD_46')
check_const('K_WORLD_47')
check_const('K_WORLD_48')
check_const('K_WORLD_49')
check_const('K_WORLD_50')
check_const('K_WORLD_51')
check_const('K_WORLD_52')
check_const('K_WORLD_53')
check_const('K_WORLD_54')
check_const('K_WORLD_55')
check_const('K_WORLD_56')
check_const('K_WORLD_57')
check_const('K_WORLD_58')
check_const('K_WORLD_59')
check_const('K_WORLD_60')
check_const('K_WORLD_61')
check_const('K_WORLD_62')
check_const('K_WORLD_63')
check_const('K_WORLD_64')
check_const('K_WORLD_65')
check_const('K_WORLD_66')
check_const('K_WORLD_67')
check_const('K_WORLD_68')
check_const('K_WORLD_69')
check_const('K_WORLD_70')
check_const('K_WORLD_71')
check_const('K_WORLD_72')
check_const('K_WORLD_73')
check_const('K_WORLD_74')
check_const('K_WORLD_75')
check_const('K_WORLD_76')
check_const('K_WORLD_77')
check_const('K_WORLD_78')
check_const('K_WORLD_79')
check_const('K_WORLD_80')
check_const('K_WORLD_81')
check_const('K_WORLD_82')
check_const('K_WORLD_83')
check_const('K_WORLD_84')
check_const('K_WORLD_85')
check_const('K_WORLD_86')
check_const('K_WORLD_87')
check_const('K_WORLD_88')
check_const('K_WORLD_89')
check_const('K_WORLD_90')
check_const('K_WORLD_91')
check_const('K_WORLD_92')
check_const('K_WORLD_93')
check_const('K_WORLD_94')
check_const('K_WORLD_95')

check_const('K_KP0')
check_const('K_KP1')
check_const('K_KP2')
check_const('K_KP3')
check_const('K_KP4')
check_const('K_KP5')
check_const('K_KP6')
check_const('K_KP7')
check_const('K_KP8')
check_const('K_KP9')
check_const('K_KP_PERIOD')
check_const('K_KP_DIVIDE')
check_const('K_KP_MULTIPLY')
check_const('K_KP_MINUS')
check_const('K_KP_PLUS')
check_const('K_KP_ENTER')
check_const('K_KP_EQUALS')

check_const('K_UP')
check_const('K_DOWN')
check_const('K_RIGHT')
check_const('K_LEFT')
check_const('K_INSERT')
check_const('K_HOME')
check_const('K_END')
check_const('K_PAGEUP')
check_const('K_PAGEDOWN')

check_const('K_F1')
check_const('K_F2')
check_const('K_F3')
check_const('K_F4')
check_const('K_F5')
check_const('K_F6')
check_const('K_F7')
check_const('K_F8')
check_const('K_F9')
check_const('K_F10')
check_const('K_F11')
check_const('K_F12')
check_const('K_F13')
check_const('K_F14')
check_const('K_F15')

check_const('K_NUMLOCK')
check_const('K_CAPSLOCK')
check_const('K_SCROLLOCK')
check_const('K_RSHIFT')
check_const('K_LSHIFT')
check_const('K_RCTRL')
check_const('K_LCTRL')
check_const('K_RALT')
check_const('K_LALT')
check_const('K_RMETA')
check_const('K_LMETA')
check_const('K_LSUPER')
check_const('K_RSUPER')
check_const('K_MODE')
check_const('K_COMPOSE')

check_const('K_HELP')
check_const('K_PRINT')
check_const('K_SYSREQ')
check_const('K_BREAK')
check_const('K_MENU')
check_const('K_POWER')
check_const('K_EURO')
check_const('K_UNDO')

check_const('K_LAST')

check_const('KMOD_NONE')
check_const('KMOD_LSHIFT')
check_const('KMOD_RSHIFT')
check_const('KMOD_LCTRL')
check_const('KMOD_RCTRL')
check_const('KMOD_LALT')
check_const('KMOD_RALT')
check_const('KMOD_LMETA')
check_const('KMOD_RMETA')
check_const('KMOD_NUM')
check_const('KMOD_CAPS')
check_const('KMOD_MODE')
check_const('KMOD_RESERVED')

check_const('KMOD_CTRL')
check_const('KMOD_SHIFT')
check_const('KMOD_ALT')
check_const('KMOD_META')

check_const('ANYFORMAT')
check_const('ASYNCBLIT')
check_const('DOUBLEBUF')
check_const('HWACCEL')
check_const('HWPALETTE')
check_const('HWSURFACE')
check_const('FULLSCREEN')
check_const('OPENGL')
check_const('OPENGLBLIT')
check_const('RESIZABLE')
check_const('RLEACCEL')
check_const('SRCALPHA')
check_const('SRCCOLORKEY')
check_const('SWSURFACE')
check_const('PREALLOC')

check_const('GL_RED_SIZE')
check_const('GL_GREEN_SIZE')
check_const('GL_BLUE_SIZE')
check_const('GL_ALPHA_SIZE')
check_const('GL_BUFFER_SIZE')
check_const('GL_DOUBLEBUFFER')
check_const('GL_DEPTH_SIZE')
check_const('GL_STENCIL_SIZE')
check_const('GL_ACCUM_RED_SIZE')
check_const('GL_ACCUM_GREEN_SIZE')
check_const('GL_ACCUM_BLUE_SIZE')
check_const('GL_ACCUM_ALPHA_SIZE')
check_const('GL_STEREO')
check_const('GL_MULTISAMPLEBUFFERS')
check_const('GL_MULTISAMPLESAMPLES')
check_const('GL_SWAP_CONTROL')
check_const('GL_ACCELERATED_VISUAL')

check_const('NOEVENT')
check_const('ACTIVEEVENT')
check_const('KEYDOWN')
check_const('KEYUP')
check_const('MOUSEMOTION')
check_const('MOUSEBUTTONDOWN')
check_const('MOUSEBUTTONUP')
check_const('JOYAXISMOTION')
check_const('JOYBALLMOTION')
check_const('JOYHATMOTION')
check_const('JOYBUTTONDOWN')
check_const('JOYBUTTONUP')
check_const('VIDEORESIZE')
check_const('VIDEOEXPOSE')
check_const('QUIT')
check_const('USEREVENT')
check_const('SYSWMEVENT')
check_const('ALLEVENTS')
check_const('NUMEVENTS')

check_const('ACTIVEEVENTMASK')
check_const('KEYDOWNMASK')
check_const('KEYUPMASK')
check_const('KEYEVENTMASK')
check_const('MOUSEMOTIONMASK')
check_const('MOUSEBUTTONDOWNMASK')
check_const('MOUSEBUTTONUPMASK')
check_const('MOUSEEVENTMASK')
check_const('JOYAXISMOTIONMASK')
check_const('JOYBALLMOTIONMASK')
check_const('JOYHATMOTIONMASK')
check_const('JOYBUTTONDOWNMASK')
check_const('JOYBUTTONUPMASK')
check_const('JOYEVENTMASK')
check_const('VIDEORESIZEMASK')
check_const('VIDEOEXPOSEMASK')
check_const('QUITMASK')
check_const('SYSWMEVENTMASK')

check_const('ADDEVENT')
check_const('PEEKEVENT')
check_const('GETEVENT')

check_const('IGNORE')
check_const('ENABLE')
check_const('DISABLE')
check_const('QUERY')

check_const('BUTTON_LMASK')
check_const('BUTTON_MMASK')
check_const('BUTTON_RMASK')
check_const('BUTTON_X1MASK')
check_const('BUTTON_X2MASK')

check_const('APPMOUSEFOCUS')
check_const('APPINPUTFOCUS')
check_const('APPACTIVE')

check_const('GRAB_QUERY')
check_const('GRAB_OFF')
check_const('GRAB_ON')

check_const('FALSE')
check_const('TRUE')

check_const('ALPHA_TRANSPARENT')
check_const('ALPHA_OPAQUE')

check_const('DEFAULT_REPEAT_DELAY')
check_const('DEFAULT_REPEAT_INTERVAL')

ver = SDL.VERSION()
print 'SDL Compiled Version: %d.%d.%d' % (ver.major, ver.minor, ver.patch)

ver = SDL.Linked_Version()
print 'SDL Linked Version: %d.%d.%d' % (ver.major, ver.minor, ver.patch)

rc = SDL.Init(SDL.INIT_VIDEO)
print 'SDL.Init() returns', rc

print 'SDL.WasInit(SDL.INIT_VIDEO):', SDL.WasInit(SDL.INIT_VIDEO)

print 'Setting an out-of-memory error'
SDL.Error(SDL.ENOMEM);
print 'SDL.GetError():', SDL.GetError()
print 'Clearing error'
SDL.ClearError()
print 'SDL.GetError():', SDL.GetError()

vi = SDL.GetVideoInfo()
print 'Current video size %dx%d, %d bpp' % (vi.current_w, vi.current_h,
        vi.vfmt.BitsPerPixel)

print 'Video driver name: "%s"' % SDL.VideoDriverName()

print 'calling SDL.Quit()'
SDL.Quit()
