#!/usr/bin/env python

import os
import sys
for d in filter(lambda x: x.startswith('lib.'), os.listdir('build')):
    sys.path.append(os.path.sep.join([os.getcwd(), 'build', d]))
import SDL

def check_const(name):
    sys.stdout.write('%s: %d\n' % (name, getattr(SDL, name)))

check_const('INIT_TIMER')
check_const('INIT_VIDEO')
check_const('INIT_AUDIO')
check_const('INIT_CDROM')
check_const('INIT_JOYSTICK')
check_const('INIT_EVERYTHING')
check_const('INIT_NOPARACHUTE')
check_const('INIT_EVENTTHREAD')

rc = SDL.Init(SDL.INIT_VIDEO)
print 'SDL.Init() returns', rc

print 'SDL.WasInit(SDL.INIT_VIDEO):', SDL.WasInit(SDL.INIT_VIDEO)

print 'SDL.GetError():', SDL.GetError()

print 'calling SDL.Quit()'
SDL.Quit()
